### ISSUE TITLE
Undefined property: CI_Output::$parse_exec_vars

### ISSUE THREAD

**Issue by mikepuerto** [philsturgeon/codeigniter-dwoo#2]
Getting this error with the latest stable version of CI - Can't find any reference to "parse_exec_vars" in the output library... ?

Severity: Notice
Message:  Undefined property: CI_Output::$parse_exec_vars
Filename: libraries/MY_Parser.php
Line Number: 172

**Comment by philsturgeon** [comment]
Try changing line 172 to:

```
if (CI_VERSION < 2 OR $this->_ci->output->parse_exec_vars === TRUE)
```

**Comment by philsturgeon** [comment]
Ping.

**Comment by mjsilva** [comment]
Pong!

Spoke with you in IRC earlier, just posting here to keep record:

(12:34:30 PM) mjsilva: philsturgeon: there?

(12:34:41 PM) philsturgeon: mjsilva: yep hi :)

(12:35:44 PM) mjsilva: hi m8, just trying to implement your dwoo parser, but I've an error with parse_exec_vars because I'm still using 1.7.2 (shame on me I know) any workarround for this?

(12:36:19 PM) philsturgeon: mjsilva: yeah i think i posted one on the github issues and was wait waiting for the guy to try it
(12:36:54 PM) philsturgeon: mjsilva: http://github.com/philsturgeon/codeigniter-dwoo/issues#issue/2

(12:38:21 PM) mjsilva: philsturgeon: yep that worked, thank you CI master of all ninjas ;)

**Comment by philsturgeon** [comment]
There was really no need to tell me we spoke on IRC a minute ago dude, I was just making this change and pushing it! >.<

**Comment by mjsilva** [comment]
You can never have too much logs :)
